import { ChildProcess } from 'child_process';
import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = (props) => {
	return (
		<>
			<Head>
				<title>Shakki =D Appi =D</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.container}>
					<h1 className={styles.title}>
						Shakki <span className={styles.pinkSpan}>=D</span> Appi
						<span className={styles.pinkSpan}>=D</span>
					</h1>
					<div className={styles.cardRow}></div>
				</div>
			</main>
		</>
	);
};

export default Home;

export async function getServerSideProps() {
	if (localStorage.getItem('moves')) {
	}
	// Fetch data from external API
	const res = await fetch(`localhost:3000/`);
	const data = await res.json();

	// Pass data to the page via props
	return { props: { data } };
}
